title: Microsoft Azure User Group Poland
description: >
  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
url: "https://azurecommunity.pl"
baseurl: ""

locale: pl_PL
timezone: Europe/Warsaw

twitter:
  username: AzureGroupPL
  card: summary

facebook:
  publisher: 933066520134721
  admins: 1234

exclude:
- assets/scss
- docs
- Dockerfile
- docker.sh
- create_Gemfile.lock.sh
- Gemfile
- Gemfile.lock
sass:
  style: compressed
  sass_dir: assets/scss

feed:
  posts_limit: 10

collections:
  og-images:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: blog/:title
      layout: post
  - scope:
      path: ""
      type: og-images
    values:
      permalink: og-image/:title
      layout: og-image
  
page_gen-dirs: true

page_gen:
  - data: 'authors'
    template: 'autopage_author'
    name: 'github'
    dir: 'author'

autopages:
  enabled: true
  categories:
    layouts: 
      - 'autopage_categories.html'
    title: 'Wszytskie strony z tagiem :cat' # :tag is replaced by the tag name
    permalink: '/category/:cat'
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Wszytskie strony z tagiem :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false

pagination:
  enabled: true
  per_page: 5
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 1
    after: 1